# SPDX-FileCopyrightText: 2026 Piotr P. Karwasz <piotr@github.copernik.eu>
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "quarterly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7